services:
  - type: web
    name: equisproject-online
    runtime: node
    buildCommand: npm install -g bun && bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
